const mongoose=require("mongoose");
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true,
    },
    image:{
        type:String,
        default:"https://imgs.search.brave.com/sHfS5WDNtJlI9C_CT2YL2723HttEALNRtpekulPAD9Q/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA2LzMzLzU0Lzc4/LzM2MF9GXzYzMzU0/Nzg0Ml9BdWdZemV4/VHBNSjl6MVljcFRL/VUJvcUJGMENVQ2sx/MC5qcGc"
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    losts:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Lost'
       }
    ],
    founds:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Found'
      }
    ],
    check:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
      }
    ]
},{timeStams:true});

module.exports=mongoose.model("User",userSchema);                                              